### ISSUE TITLE
[BUG] This plugin causes stuttering

### ISSUE THREAD

**Issue by Siggy101** [Renaud11232/OctoPrint-Resource-Monitor#38] opened 2022-05-21 14:24 UTC
**Describe the bug**

Installed on OctoPrint a RPi 3B+ running OctoPrint 1.8.0, this plugin causes the Ender 3v2 to stutter all through a print job.

**To Reproduce**

Print anything with this plugin enabled.
If I disable this plugin, and only this plugin, the printer runs smoothly again.

**Expected behavior**

Print smoothly without stuttering

**Version of OctoPrint-Resource-Monitor**

0.3.6 installed via the Octoprint plugin manager

**Comment by Renaud11232** [comment] 2022-05-21 14:34
Hello, I am aware of this issue affecting multiple users.
But, so far, I can't reproduce it on my own printer nor can't find what causes this.

I'm closing this issue since this is a duplicate of #37

**Closed as completed by Renaud11232** 2022-05-21 14:34 UTC
Labels: bug, duplicate

**Comment by Siggy101** [comment] 2022-05-21 19:50
Ah, sorry, I missed that other bug report.
I shall follow the other then.  I can post up my gcode and a video, if it helps.
