### ISSUE TITLE
How to add more temperature sensor?

### ISSUE THREAD

**Issue by JostenSyon** [Renaud11232/OctoPrint-Resource-Monitor#33] opened 2021-09-02 19:27 UTC
I installed the plugin in a Ubuntu server system.

I use `sensors -A acpitz-virtual-0` to check the temperature and use a grep on it to filter the temperature 
`grep -A 0 'temp1' | cut -c13-24`

Can be possible to integrate it? Maybe adding a field into the setting page to put a custom code so in will not be hardcoded?

thanks in advance

**Comment by Renaud11232** [comment] 2021-09-05 13:41
Hello,

This is a duplicate of #28 

I will look into adding this in the future, but I currently don't have the time to work on this plugin.

I'll give it a shot in the future.

Since this is the same as issue #28, I'll be closing this one

**Closed as completed by Renaud11232** 2021-09-05 13:41 UTC
Labels: duplicate, enhancement
