### ISSUE TITLE
[BUG] PermissionError when attempting to get resource usage information on android (octo4a)

### ISSUE THREAD

**Issue by j-snijder** [Renaud11232/OctoPrint-Resource-Monitor#40] opened 2022-10-30 18:59 UTC
The feature I like to see is NOT related to a problem with octoprint as persé, but more as a problem loading in octo4a (which is a derivate of octoprint)
After installation there should be, but is not, a new tab where we can see the graphs with information.
  
I'd lik to see a compatibility with octoa, if you could be so nice :)

Please help out, as more and more people are discovering the use of octo4a in stead of the RP option for which people need to be a rocket sciëntist to get it up and running. :)

**Comment by Renaud11232** [comment] 2022-10-31 09:10
Hello,

I don't know much about octo4a more specifically how plugins are handled/installed.
Can you please provide octoprint logs ?

Thanks

**Comment by j-snijder** [comment] 2022-10-31 11:09
Hi

The logfile is completely empty so nothing is logged, sorry.

**Comment by j-snijder** [comment] 2022-10-31 11:12
[octoprint-logs (1).zip](https://github.com/Renaud11232/OctoPrint-Resource-Monitor/files/9900546/octoprint-logs.1.zip)
What I can provide you with is the octoprint log itself, perhaps thats good enough ?

**Comment by Renaud11232** [comment] 2022-10-31 12:17
Hello,

Yes I meant octoprint logs. That's perfect.
This issue appears to actually be a bug that is not specific to octo4a.

I just published a release candidate that should fix the issue.
Can you try to install it manually using the following URL through the plugin manager (Settings > Plugin Manager > Get more > from URL) : https://github.com/Renaud11232/OctoPrint-Resource-Monitor/archive/refs/tags/0.3.10rc1.zip

If that didn't work, can you send your latest logs again ?

Thanks

**Comment by j-snijder** [comment] 2022-10-31 13:43
Hi 😁 as I always say, coincedense doe not exist, everything is ment to be 🤣I'll install it this afternoon and contact you asapKind regards JanOp 31 okt. 2022 13:17 schreef Renaud11232 ***@***.***>:
Hello,
Yes I meant octoprint logs. That's perfect.
This issue appears to actually be a bug that is not specific to octo4a.
I just published a release candidate that should fix the issue.
Can you try to install it manually using the following URL through the plugin manager (Settings > Plugin Manager > Get more > from URL) : https://github.com/Renaud11232/OctoPrint-Resource-Monitor/archive/refs/tags/0.3.10rc1.zip
If that didn't work, can you send your latest logs again ?
Thanks

**Comment by j-snijder** [comment] 2022-10-31 15:47
[octoprint-logs.zip](https://github.com/Renaud11232/OctoPrint-Resource-Monitor/files/9902610/octoprint-logs.zip)
Hi,

Installed the beta version and sorry to say but still nothing to see, no new tab, no entry in the plugin listing.
As before there is a logfile created but empty as before (attached it also for you to see)

Are there some specific prerequests to this plugin ? is it neccesary to have some other plugins installed on what it is depending on ?

Like to help out in testing if needed to.

Kind regards, Jan

**Comment by Renaud11232** [comment] 2022-11-11 12:40
Hello,

It appears that the first issue was in fact hiding the next one which is specific to android.
I've just published a new prerelease that addresses that issue and should allow the plugin to run : https://github.com/Renaud11232/OctoPrint-Resource-Monitor/archive/refs/tags/0.3.10rc2.zip
I hope there isn't another issue down the line.
However, that also means that some (or all) partitions won't appear in the plugin tab. This is due to the fact that Android does not give read access to the files needed to get disk usage information. I don't see any way to work around that.

Can you tell me if that worked ?

**Comment by j-snijder** [comment] 2022-11-13 12:37
Hi,Sorry,stil not working, nothing shows upRegards, JanOp 11 nov. 2022 13:41 schreef Renaud GASPARD ***@***.***>:
Hello,
It appears that the first issue was in fact hiding the next one which is specific to android.
I've just published a new prerelease that addresses that issue and should allow the plugin to run : https://github.com/Renaud11232/OctoPrint-Resource-Monitor/archive/refs/tags/0.3.10rc2.zip
I hope there isn't another issue down the line.
However, that also means that some (or all) partitions won't appear in the plugin tab. This is due to the fact that Android does not give read access to the files needed to get disk usage information. I don't see any way to work around that.
Can you tell me if that worked ?

**Comment by Renaud11232** [comment] 2022-11-13 16:04
Can you provide more recent logs to see if any new issue showed up ?

**Comment by j-snijder** [comment] 2022-11-13 19:59
Hi,

Sorry it took so long, had to do a uninstall of the previous version and a fresh install of your last updated version.

Attached is the octoprint log
[octoprint.log](https://github.com/Renaud11232/OctoPrint-Resource-Monitor/files/9998099/octoprint.log)

**Comment by Renaud11232** [comment] 2022-11-15 10:10
Hello,

Once again, this issue was hidden by the previous one. I hope there won't be anymore suprises.
Can you try to install this version : https://github.com/Renaud11232/OctoPrint-Resource-Monitor/archive/refs/tags/0.3.10rc3.zip and report if that fixed the problem ?

If not, please provide recent logs.
Thanks for your patience

**Comment by j-snijder** [comment] 2022-11-15 11:08
Hi :(

Sorry to say that it still does not show up, neither in the plugins list nor as a tab in octoprint :(

But... together we stand strong :)

[octoprint (1).log](https://github.com/Renaud11232/OctoPrint-Resource-Monitor/files/10012037/octoprint.1.log)

**Comment by Renaud11232** [comment] 2022-11-27 14:27
Hello,

I've managed to successfully install octo4a on 2 devices and got the plugin to run on those two devices with a new prerelease. (https://github.com/Renaud11232/OctoPrint-Resource-Monitor/archive/refs/tags/0.3.10rc4.zip)

However, due to android file permissions being so restrictive, the plugin fails to gather a lot of resource usage information : 
* On the 1st test device, some disk usage info & some network usage could be gathered and displayed.
* While on the 2nd device, only RAM & CPU usage could be monitored (with some data looking abnormal).

This will probably be different on other devices and/or might even render the plugin completely useless.

Can you tell me if that version worked ? (It might be pretty empty due to android file permissions)
If not, can you once again provide up to date logs ?

Thanks a lot for your help

**Comment by j-snijder** [comment] 2022-12-01 20:05
Hi,
Sorry for my late reaction, had my birthday so got a lot of gifts I wanted to implement on my printer (mega upgrades :) )

Okay, installed the latest rc4 and it works on a lot of stuff, though the screen look very strange (i'll attach some screens for you to examine.

Perhaps its in the way I (did not yet) setup the app)

![2022-12-01 (1)](https://user-images.githubusercontent.com/36368735/205148949-19aa676a-3644-4483-a5f5-676b8627541b.png)
![2022-12-01 (2)](https://user-images.githubusercontent.com/36368735/205148953-05299c05-1474-4d60-b118-ac8ad365543b.png)
![2022-12-01](https://user-images.githubusercontent.com/36368735/205148956-8cfbb7fe-a99f-450c-81cc-e9b342ca8fe0.png)

**Comment by j-snijder** [comment] 2022-12-01 20:08
Memory
Network 4
Network 15
Battery

All seem to work, on my Samsung A5 (2017)
![2022-12-01 (2)](https://user-images.githubusercontent.com/36368735/205149522-c89fc933-86f2-4292-96d6-371b88d1a1c5.png)
![2022-12-01 (3)](https://user-images.githubusercontent.com/36368735/205149525-8b1a4fd2-28e5-41dc-b812-e48ec8c9f58d.png)
![2022-12-01 (4)](https://user-images.githubusercontent.com/36368735/205149526-c3fe4036-ac89-4e9e-b5ab-4b6f5ccdf760.png)
![2022-12-01 (5)](https://user-images.githubusercontent.com/36368735/205149528-e3a4981c-a33c-4abb-9925-1b6449abbd04.png)

**Comment by j-snijder** [comment] 2022-12-01 20:32
Processor seems to work and reports Cores, threads and processes but shows no graph 

Kind regards, maybe this helps you to solve the plugin not working on octo4a

**Comment by Renaud11232** [comment] 2022-12-02 08:34
Hello,

Can you please set the plugin logging to DEBUG and provide the logs once again.
To set it to DEBUG, you need to go in Octoprint settings -> Logging -> Logging Levels
![image](https://user-images.githubusercontent.com/13933802/205249146-b4dbbda6-44ea-420f-b246-610b467aa9c3.png)

Once you have sent the logs, you can remove that log configuration to avoid unnecessary logging.

Thanks

**Comment by j-snijder** [comment] 2022-12-04 15:01
I have deinstalled the plugin for now, something is causing big problems in octoprint resulting in heavy processor use and very bad printing as a result.Have to find out, after removing this plugin things got better but not fully back to normal.All started after installing the v3 of your fix 😁I'll get back to you, but if I forget and you haven't heard from me in a week please remind me.Regards Op 2 dec. 2022 09:34 schreef Renaud GASPARD ***@***.***>:
Hello,
Can you please set the plugin logging to DEBUG and provide the logs once again.
To set it to DEBUG, you need to go in Octoprint settings -> Logging -> Logging Levels

Once you have sent the logs, you can remove that log configuration to avoid unnecessary logging.
Thanks

**Comment by Renaud11232** [comment] 2022-12-17 13:36
Hello,

Have you had the time to look into this ?

THanks

**Comment by j-snijder** [comment] 2022-12-17 16:49
I'll try tonight okay ? Grandchildren now in tha house 🤣🙈 disaster time,😂Op 17 dec. 2022 14:36 schreef Renaud GASPARD ***@***.***>:
Hello,
Have you had the time to look into this ?
THanks

**Comment by j-snijder** [comment] 2022-12-17 21:25
Hi,

I'm sorry to report that resource manager does not log , not one bit, the logfile: octoprint.plugins.resource_monitor,   is not shown in the list of logfiles, therefore not downloadable.
The file :  octoprint.plugins.resource_monitor.profiling, does show but is 0 bites.

![2022-12-17](https://user-images.githubusercontent.com/36368735/208266541-53d6dea6-3691-4498-b726-da9da563a273.png)

**Comment by Renaud11232** [comment] 2022-12-18 09:32
When you set the debug level to `DEBUG`, the plugin does not create a new file but keeps logging in the `octoprint.log` with more details.
`octoprint.plugins.resource_monitor.profiling` should not contain anything as it's used only if you enable an option which is not required here.

Can you please provide the contents of octoprint.log when you have the logging level set to `DEBUG`.

Once you have sent the logs, you can remove the `DEBUG` logging configuration to avoid unnecessary logs.

Thanks & sorry if it wasn't clear.

**Comment by j-snijder** [comment] 2022-12-18 11:43
Hmmm, logfile too big, max is 25 Mb file is 28 Mb, i'll delete all logs and start a few prints to create a new one

**Comment by Renaud11232** [comment] 2022-12-18 12:40
You should be able to upload it here : https://www.dropbox.com/request/P5LetK5NfxccD1m7dKrb

**Comment by j-snijder** [comment] 2022-12-18 12:47
Hi, sorry but a new problem occured.

As I deleted the old logfiles now octoprint is no longer logging anythin anymore, even if I tell specificly to log certain files.

I'll upload my old log to your dropbox.

regards, Jan

**Comment by j-snijder** [comment] 2022-12-18 12:48
Done uploading to your dropbox.

regards, Jan

**Comment by Renaud11232** [comment] 2022-12-26 09:15
Hello,

I have not been able to reproduce the layout issue with the strange graph placement. Even after installing the same plugins as you. However I think it might be linked to one of the UI plugins you are using, maybe with a specific configuration.

I don't think I can't do much if the CPU graphs don't show anything as `psutil` (the library I'm using to get resource usage stats) does return 0 all the time in this case.

The only way to know which one is to disable them until everything works out normally.

I'm sorry if what I'm asking sounds tedious but can you try disabling your plugins one by one until the graphs show up normally ? And then tell me which one it was (maybe with its configuration) so I can see if I can do something to fix that ?

Once again, thank you

**Comment by j-snijder** [comment] 2022-12-26 20:53
Hi 😁As octo4a gives me lots of problems lately I have left the programm for now, if and when I have the time to see whats wrong I'll try your options and remove the plugins to test.That, will be somewhere end January at its earlyest, sorry to say.In the meantime I wish you a happy newyear and whats left of Christmas 😁Greets, JanOp 26 dec. 2022 10:15 schreef Renaud GASPARD ***@***.***>:
Hello,
I have not been able to reproduce the layout issue with the strange graph placement. Even after installing the same plugins as you. However I think it might be linked to one of the UI plugins you are using, maybe with a specific configuration.
I don't think I can't do much if the CPU graphs don't show anything as psutil (the library I'm using to get resource usage stats) does return 0 all the time in this case.
The only way to know which one is to disable them until everything works out normally.
I'm sorry if what I'm asking sounds tedious but can you try disabling your plugins one by one until the graphs show up normally ? And then tell me which one it was (maybe with its configuration) so I can see if I can do something to fix that ?
Once again, thank you

**Comment by bend1215** [comment] 2023-01-17 21:14
Hey thanks for putting such a cool plugin together.

I'm also running Octo4a but on a Pixel 3. Using the main release I also was missing the added tab. Using the latest release above I got an empty CPU usage graph but a working RAM graph, no other readouts:
![Screenshot 2023-01-16 195921](https://user-images.githubusercontent.com/122853754/213012131-f9f9c996-dc27-419e-9bbe-51f60983956b.png)

Seems as though its the same problem as the other user, not sure if you're looking for more logs, I think I've followed the settings you gave above. 
[octoprint.log](https://github.com/Renaud11232/OctoPrint-Resource-Monitor/files/10439376/octoprint.log)

I'm primarily interested in the temperature monitoring as this has been the only reason the phone controlled printing has been unstable. It would be nice to be able to monitor its temperature and shut down the IP cam streams for example. 

Thanks again!

**Comment by Renaud11232** [comment] 2023-01-21 08:55
Hello @bend1215,

It looks like you set the logging level of `octoprint.plugins.resource_monitor.profiling` to `DEBUG`.
Can you try again with `octoprint.plugins.resource_monitor` (without `.profiling` at the end) instead and then upload newer logs here ?

That being said, I see that the plugin could not get some resource stats due to android file permissions, I don't think there's a way to prevent that behaviour. In this case a `PermissionError` occured when trying to get : 
* CPU frequency
* disk partitions usage
* network interface usage
* battery stats

Thank you for your understanding

**Comment by Renaud11232** [comment] 2023-04-10 18:27
Closing since I can't get arround android permissions

**Closed as not planned** 2023-04-10 18:26 UTC
Labels: bug, wontfix
